# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 06:06
from __future__ import unicode_literals

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=simditor.fields.RichTextField(default=''),
        ),
    ]
